package com.vladte.devhack.service.api;

import java.util.List;

/**
 * Interface for parsing generated text into question texts.
 */
public interface QuestionParsingService {

    /**
     * Parse the generated text into a list of question texts.
     *
     * @param generatedText the text generated by the AI
     * @return a list of question texts
     */
    List<String> parseQuestionTexts(String generatedText);
}